# This is a basic workflow to help you get started with Actions

name: Rolling build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature/*, fix/*, release/*, Architecture ]
  pull_request:
    branches: none

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout Git
        with:
          submodules: recursive
    
      - name: Install CMake
        # You may pin to the exact commit or the version.
        # uses: Symbitic/install-cmake@301e932c0011b8d12d8bf33d4975fd1e17972709
        uses: Symbitic/install-cmake@v0.1.0
    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      
      - name: CMake configure
        run: cmake --preset Debug
        
      - name: CMake build
        run: |
          cd out/build/Debug |
          cmake --build
